### ISSUE TITLE
Copy header phase happens before compile phase

### ISSUE THREAD

**Issue by samdmarshall** [facebook/xcbuild#13] opened 2016-01-27 20:24 UTC
I'm noticing on the output of xcbuild that it will output the copy-header phases before performing a compile, this doesn't respect the ordering that Xcode has for a build or the ordering that the phases have in the project file.

**Comment by samdmarshall** [comment] 2016-03-02 18:35
Is this currently resolved? I tried the build again and it seems to be executing in order now.

**Comment by grp** [comment] 2016-03-02 18:47
I think it's pretty much random. With the normal executor, the directed graph of invocations uses a `std::unordered_set` so it's however that decides to sort itself. The Ninja executor is probably a more deterministic but I'm not sure how.

**Comment by samdmarshall** [comment] 2016-03-02 18:52
OK because I am not seeing the same build errors as before but I don't know if it is happening by chance or not. There should probably be a note on the homepage to let people know what to expect about this behavior.

**Comment by orta** [comment] 2016-03-02 18:53
I got a version of Artsy/Eigen building, but I'm not using ninja yet, FWIW

**Comment by samdmarshall** [comment] 2016-03-08 15:14
Is there any reason why the code needs to use an unordered set for storing the build phases? By changing that to an array wouldn't it cause successful builds because of preserved ordering?

**Comment by grp** [comment] 2016-03-08 17:18
The issue is that it's not a set vs an array — that's just the storage for a directed graph stored as an adjacency list (see [`DirectedGraph.h`](https://github.com/facebook/xcbuild/blob/master/Libraries/pbxbuild/Headers/pbxbuild/DirectedGraph.h)) used for the topological sort (which also doesn't preserve linear ordering).

Although, the directed graph isn't used for phases at all right now, since phases are completely dropped before ordering time and it just looks at invocations. This is also true for targets, though, and those do handle ordering correctly by having extra dependency edges added from an invocation to the containing target. A similar approach should work ordering for build phases, and would let user-defined scripts fit in the right place without limiting parallelism for phases that don't have such strong ordering requirements.

**Comment by samdmarshall** [comment] 2016-03-08 17:58
Ah, I see. Part of my concern here is the deviation from the expected behavior of the `xcodebuild` build process to more favour parallelism. In my opinion I think this is a poor optimization as in the vast majority of cases you will not see a significant speed-up in overall execution time. The only parts of the build system that supports parallelizing builds, that I am aware of, are of implicit dependency targets that are dispatched independently from the scheme level. 

If your goal here is to make something compatibile with Xcode's build system then I think you will need to drop the parallelism here. However if this is something specific to buck and whatever builds coindentally work as well then I wouldn't want to advertise it as "compatible with Xcode". 

Speaking for myself, I would like to use this for building on older platforms that don't support the latest versions of Xcode. However, that is made complicated by the parallelized phases and causing builds to be performed inconsistently. The outcome of this ticket ultimately dictates if I will use this or finish building the two tools I've written that serve as `xcodebuild` replacements.

**Comment by grp** [comment] 2016-03-08 18:17
No, this is definitely a bug that should be fixed. Just still need to find the right way to get around it — whether it's finding a good topological sorting algorithm, inserting barrier edges in the graph, or something else. Will discuss more internally & take a look soon.

**Comment by samdmarshall** [comment] 2016-03-08 18:41
OK, sounds good. are you still able to parallelize the compiling individual files? I work with a bunch of projects that would benefit from the ability to do that. There isn't much I can do with the code as I'm not signing Facebook's CLA (sorry, not sorry), but if there is anything I can do please let me know.

**Comment by grp** [comment] 2016-03-08 19:13
Yeah, it should still be able to parallelize parts using built-in tools that xcbuild can verify don't need phase-based ordering. There will still necessarily be a barrier around user shell script phases (or rules), but should keep parallelism.

**Closed** 2019-03-10 22:00 UTC
